syntax = "proto3";

option java_multiple_files = true;
option java_package = "edu.eci.arsw.wellness";
option java_outer_classname = "AppointmentProto";

service AppointmentService {
  rpc RequestAppointment (AppointmentRequest) returns (AppointmentResponse);
  rpc CancelAppointment (CancelRequest) returns (CancelResponse);
  rpc GetAppointments (StudentRequest) returns (AppointmentList);
}

message Student {
  string id = 1;
  string name = 2;
  string institutionalEmail = 3;
}

message Appointment {
  string id = 1;
  string studentId = 2;
  ServiceType serviceType = 3;
  string date = 4;
  Status status = 5;
}

enum ServiceType {
  SERVICE_TYPE_UNSPECIFIED = 0;
  MEDICINE = 1;
  PSYCHOLOGY = 2;
  DENTISTRY = 3;
}

enum Status {
  STATUS_UNSPECIFIED = 0;
  REQUESTED = 1;
  CANCELLED = 2;
  ATTENDED = 3;
}

message AppointmentRequest {
  Student student = 1;
  ServiceType serviceType = 2;
  string date = 3;
}

message AppointmentResponse {
  Appointment appointment = 1;
  bool success = 2;
  string message = 3;
}

message CancelRequest {
  string appointmentId = 1;
  string studentId = 2;
}

message CancelResponse {
  bool success = 1;
  string message = 2;
}

message StudentRequest {
  string studentId = 1;
}

message AppointmentList {
  repeated Appointment appointments = 1;
}
