syntax = "proto3";

import "common.proto";

option java_multiple_files = true;
option java_package = "edu.eci.arsw.wellness.ms";
option java_outer_classname = "GymProto";

service GymService {
  rpc ReserveGymSession (GymReservationRequest) returns (GymReservationResponse);
  rpc GetGymReservations (StudentRequest) returns (GymReservationList);
}

message GymReservationRequest {
  string studentId = 1;
  string timeSlot = 2;
}

message GymReservation {
  string id = 1;
  string studentId = 2;
  string timeSlot = 3;
  string status = 4;
}

message GymReservationResponse {
  GymReservation reservation = 1;
  bool success = 2;
  string message = 3;
}

message GymReservationList {
  repeated GymReservation reservations = 1;
}
