syntax = "proto3";

import "common.proto";

option java_multiple_files = true;
option java_package = "edu.eci.arsw.wellness.ms";
option java_outer_classname = "RecreationProto";

service RecreationService {
  rpc ReserveRecreationResource (RecreationReservationRequest) returns (RecreationReservationResponse);
  rpc GetRecreationReservations (StudentRequest) returns (RecreationReservationList);
}

message RecreationReservationRequest {
  string studentId = 1;
  string resourceId = 2;
}

message RecreationReservation {
  string id = 1;
  string studentId = 2;
  string resourceId = 3;
  string status = 4;
}

message RecreationReservationResponse {
  RecreationReservation reservation = 1;
  bool success = 2;
  string message = 3;
}

message RecreationReservationList {
  repeated RecreationReservation reservations = 1;
}
